### ISSUE TITLE
homework folders in our private directory: is name important?

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Exemplars#1]
Step 3 in the instructions for hw00-1 ([here]( https://www.cs.tufts.edu/comp/150PLD/hw00-1.html)) says: 
> Copy the hw00-1-programming-languages-in-the-wild/template.md **into the hw00-1 directory in your private repo**

Does the name of the hw00-1 directory matter? (will it mess with the backend grading if I misname a directory at some point?)

**Comment by mpahrens** [comment]
Thank you for the question.

Please make a directory in your private repo and it doesn't necessarily matter what you name it since grading is not automated.

Thanks!
