### ISSUE TITLE
Clarify Q9 of Template Haskell

### ISSUE THREAD

**Issue by maddoschwartz** [150PLD-Fall2019/Exemplars#10]
Hi there! Question 9 reads:

> What happens, and under what conditions, and when a Template Haskell program diverges for some input.

Can you please clarify by what you mean with "diverge" and "input"? Is it correct to interpret diverge as nondeterministic behavior and input as IO? 

Thanks!

**Comment by mpahrens** [comment]
I apologize for not seeing this in time for the homework itself, but I hope today's class discussion answered this question for you. 
As a side note for everyone, please don't stress if you miss a question here and there. 
Your overall achievement of the learning objectives isn't tied to being perfect, so
these reading comprehensions should be achieved as a best effort.
