### ISSUE TITLE
HW4: matching test7 with output of #6 runYourStatefulProgram

### ISSUE THREAD

**Issue by jingqiyang** [150PLD-Fall2019/Exemplars#11]
From my understanding, `runState` returns a tuple in the form `(value in the final type parameter, state)`. `runYourStatefulProgram` returns the first element of this tuple, while the expression that it should match with in the test case looks to be the tuple returned from `runState` (assuming that the hash map represents the state). Why is that? Is the overall tuple supposed to be wrapped in another tuple?

**Comment by natebragg** [comment]
It suffices to fix the problem if you remove the call to `fst`.

**Comment by jingqiyang** [comment]
@natebragg Yes I'm aware, I was asking to confirm that fst should indeed be removed

**Comment by mpahrens** [comment]
Thank you for this! 
I pushed the fixed version with the call to fst removed
