### ISSUE TITLE
`stack build` does not work because of 'Disk quota exceeded'

### ISSUE THREAD

**Issue by duci9y** [150PLD-Fall2019/Exemplars#12]
Output:

```
dutkar01@vm-hw02 ~/c/d/h/familiar-functions> stack build
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                
/usr/bin/tar: ghc-8.6.5/libraries/Cabal/Cabal/dist-install/build/Distribution/Parsec/Class.p_hi: Cannot close: Disk quota exceeded
```

I have already requested more disk quota, but is there another way to fix this?

**Comment by merterden98** [comment]
Have you tried the following?
```bash
cd
rm -rf .cache
```
this should clear some space

**Comment by duci9y** [comment]
Yes, I did. No luck :(

**Comment by merterden98** [comment]
@mpahrens is it possible to install haskell on admin to access from `/bin/` or is it the case that IT is afraid to introduce potential regressions into Halligan?

**Comment by mpahrens** [comment]
We have a solution for this.
First, delete your local copy of ghc by `rm -rf ~/.stack`.
Second, you can add the system installation of ghc and stack to your path with `use comp150pld`.
Third, make a tmp directory in your home or somewhere you have access to: `mkdir ~/tmp`
Fourth, add the tmp to an environment variable so stack can find it: `export TMPDIR="~/tmp"` or `setenv TMPDIR ~/tmp`.
Lastly, run stack like so: `stack build --system-ghc` `stack repl --system-ghc`.

Let me know how you fair with these instructions.

**Comment by duci9y** [comment]
So an update:

I ran into another disk quota error with those commands. Meanwhile I setup stack and GHC on my personal computer just so I could move forward and not be stuck. I tried the commands again today after making sure I started from scratch it works! Thank you for your help. I will catch up on homework this week.
