### ISSUE TITLE
Can we go over the whatDoesThisExpDo2 (Tree Example) tomorrow? 

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#14]
Thanks :)

**Comment by jaredchandler** [comment]
data q2 = Confusion | Pain 
whatDoesThisExpDo2 :: student -> q2

**Comment by mpahrens** [comment]
@dgrotenstein  Yes we can! 
@jaredchandler your code snippet is not valid haskell as Prefix Type Constructors in haskell must start with a capital letter (both for q2 and student types).

**Comment by mpahrens** [comment]
I still plan on going over this problem this morning, but I also recorded a small explanation so people can digest it in their own time as well.
https://youtu.be/VHOC4QAgUXg
