### ISSUE TITLE
Can you provide the text you type in your videos?

### ISSUE THREAD

**Issue by jaredchandler** [150PLD-Fall2019/Exemplars#15]
It's hard to see the text you type to follow along. 

Can you provide transcripts of what you type?

**Comment by mpahrens** [comment]
I am finding it difficult to develop transcripts for the videos. 
If someone were to transcribe for me, I'd feel that that effort would be worth extra participation credit.
I am looking for a good solution though, but do not have one as of yet.
Any suggestions are welcome.

**Comment by jmusca** [comment]
Here are screencaps of terminals from hw4:

# Video 1:
![hw04-10](https://user-images.githubusercontent.com/11913534/65191549-562d0b00-da42-11e9-94aa-5cc6a7f88bd8.jpg)

# Video 2:

![hw04-20](https://user-images.githubusercontent.com/11913534/65191550-562d0b00-da42-11e9-9201-8aeb1a457109.jpg)

![hw04-21](https://user-images.githubusercontent.com/11913534/65191551-562d0b00-da42-11e9-8e4a-7261c4d4c26b.jpg)

![hw04-22](https://user-images.githubusercontent.com/11913534/65191543-55947480-da42-11e9-8159-4dcea9d1d3e2.jpg)

![hw04-23](https://user-images.githubusercontent.com/11913534/65191544-562d0b00-da42-11e9-8d7a-44552f8e70bc.jpg)

# Video 3
![hw04-30](https://user-images.githubusercontent.com/11913534/65191545-562d0b00-da42-11e9-84e7-c66239932d46.jpg)

# Video 4
![hw04-40](https://user-images.githubusercontent.com/11913534/65191546-562d0b00-da42-11e9-9cf9-35a7bc09813e.jpg)
![hw04-41](https://user-images.githubusercontent.com/11913534/65191547-562d0b00-da42-11e9-99f2-a3074acd2209.jpg)

**Comment by duci9y** [comment]
I think it would also be helpful to use a giant font size while recording.

**Comment by mpahrens** [comment]
Thank you JM,

I'll increase the font size for the next videos.

Also, @jaredchandler  I did find a solution for this, so for hw6+ you can expect a transcript of what I enter into the repl.
