### ISSUE TITLE
For the future - Partial submissions possible?

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Exemplars#16]
I'm not going to do this for this hw, so the question is not pressing... But I was wondering if, in the future, I did part of an assignment, which met a subset of the learning objectives, I could submit what I did, with a meta.md that discussed how I met that subset of learning objectives.

**Comment by mpahrens** [comment]
Yes, whatever you submit at the time of grading will be graded on its merits, even if partial.

**Comment by jmusca** [comment]
Cool thanks!
