### ISSUE TITLE
HW01-1: Level of skill demonstration

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#2]
In the youtube video you posted for this homework, the learning objectives were labelled with 'Recognition' level skill demonstration, but the site shows them as 'Recall'. I was wondering if there was one that you felt more accurately fit what we did for this assignment.

**Comment by mpahrens** [comment]
Hi Dana, thank you for catching this! This was a mislabeling error that I thought I scrubbed, but left in the video. My apologies for the confusion.

The learning objective for hw01-1 should be Recall as it is posted on the site.
