### ISSUE TITLE
IO Monads in Depth

### ISSUE THREAD

**Issue by RemmyChen** [150PLD-Fall2019/Exemplars#22]
in the IO Monads in Depth video, the slide of irksome restrictions at 25:52 talks about two options with problems. is there a third option? in practice which option do programmers generally choose?

**Comment by mpahrens** [comment]
So, in practice what people do is write their program as a library of pure functions that take in all the information they need from the environment as a parameter.
Then, when structuring their main application, they "script" or imperatively program their side-effecting calls to the environment and pass that information to the pure functions while "inside the monad". This is most like the first option.

IF (a really big IF) the users either can guarantee the compiler won't mess up their code through optimizations by the task they are trying to do being pure (or close enough), or if the programmers really don't care, then they can use `unsafePerformIO :: IO a -> a`. Programmers typically choose this option when the stakes are low and the cost of re-structuring the code to follow the best practice above is high.
