### ISSUE TITLE
Disk Quota Exceeded

### ISSUE THREAD

**Issue by maddoschwartz** [150PLD-Fall2019/Exemplars#23]
Hi - I tried the commands mentioned in #12, but I'm still getting a Disk Quota Exceeded. How can I fix this?

**Comment by mpahrens** [comment]
Hi Maddie, 

if deleting `~/.stack` doesn't allow you to build and run assignments using `use com150pld` and `stack build --system-ghc`, please email `staff@eecs.tufts.edu` asking for an increase in your quota and CC me on the email.

Sorry you are encountering this issue.
