### ISSUE TITLE
Permission denied in stack repl

### ISSUE THREAD

**Issue by maddoschwartz** [150PLD-Fall2019/Exemplars#24]
I ran `stack repl --system-ghc` and then typed 1 to load io1. 

I then received the following error.

The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O2
Configuring GHCi with the following packages: using-monads
/tmp/haskell-stack-ghci/6ddd39a3: createDirectory: permission denied (Permission denied)

Does anybody know of any solutions to this?

**Comment by mpahrens** [comment]
an explanation is in my video here: https://www.youtube.com/watch?v=nuKTVx-mpS8&feature=youtu.be

quick fix:
- make a tmp directory stack can use somewhere you have access to. e.g. `mkdir ~/tmp`
- set the TMPDIR environment variable to point at this before you run stack `setenv TMPDIR ~/tmp`

I do not understand why I can write to /tmp and some of y'all can't. Alas, this is the best I can do for you for now.
