### ISSUE TITLE
th-examples 

### ISSUE THREAD

**Issue by RemmyChen** [150PLD-Fall2019/Exemplars#26]
can the full implementation of functions in th-examples be posted?

**Comment by mpahrens** [comment]
Thank you for reminding me. 
Solutions from class (using take and drop) should be put up by scribes in the Reading wiki. I pushed my solutions here:
https://github.com/150PLD-Fall2019/Exemplars/blob/master/th-examples/src/Lib.hs

**Comment by RemmyChen** [comment]
Thanks!
