### ISSUE TITLE
Questions that came up from HW07-1

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#28]
Just some questions that came up doing the homework, maybe we can discuss in class? 
- Why would one want a metalanguage and object language to be the same? 
- What are the differences between patterns and expressions in Haskell?
- What does it mean to extend a generic function with type-specific cases?

**Comment by mpahrens** [comment]
Yep! We are going to go over the homework as a warm up today, so we can tackle these questions at the same time
