### ISSUE TITLE
HW08-1 NOT READY FOR STUDENT CONSUMPTION ??

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#29]
Is hw8 still not ready or is that an artifact of an earlier edition? Trying to get started now :) Thanks

**Comment by RemmyChen** [comment]
and a follow up question - when trying to run $stack repl locally, i can only be in prelude and see the following : 

Writing implicit global project config file to: /Users/remmyc/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-14.7

Note: No local targets specified, so a plain ghci will be started with no
      package hiding or package options.
      
      You are using snapshot: lts-14.7

**Comment by mpahrens** [comment]
@dgrotenstein It is ready for student consumption, thank you for asking, I forgot to remove the label.
@RemmyChen I only get that issue when I run `stack repl` outside of a project folder. What folder are you running stack repl from?

**Comment by RemmyChen** [comment]
ahhh - careless mistake, you are correct
