### ISSUE TITLE
Need Volunteer to take an extra proposal to review

### ISSUE THREAD

**Issue by mpahrens** [150PLD-Fall2019/Exemplars#31]
In addition to the folks in your group from wednesday, I need 2 people to volunteer to give feedback to 1 person who was absent. 
Please volunteer in this issue.
I'll give you an extra participation credit and also consider it when assessing learning objectives. 
Thanks!

**Comment by mpahrens** [comment]
@natebragg @jaredchandler @uwaces @nw0428 @ChrisEPhifer @merterden98 @jakebennert @maddoschwartz @cdelor02 @jmusca @jingqiyang @longtran1701 @RemmyChen @dgrotenstein

**Comment by jakebennert** [comment]
I can do it!

**Comment by mpahrens** [comment]
Still need 1 more. Thanks Jake! You'll find it in the 13-2 directory of your repo

**Comment by nw0428** [comment]
I am happy to do it!

**Comment by mpahrens** [comment]
Thanks David! I'll put it in the hw13-2 directory in your private repo
