### ISSUE TITLE
I only got one proposal in my 13-2 folder

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#33]
does that mean I am only responsible for one?

**Comment by mpahrens** [comment]
Sorry,  I'm replying on my phone so I hope this goes through.

Jake was in your group,  but didn't submit a digital copy of his proposal,
so i couldn't forward it to you.  If you have a paper copy from Wednesday
use that,  otherwise just review Long's proposal.

Thanks!
