### ISSUE TITLE
Suggested Sections for Outline

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#34]
Hi! Are there suggested sections we should have for our paper / if you were to specify how we should chunk our paper broadly, what would you recommend?

**Comment by mpahrens** [comment]
My recommendation is to pick your favorite paper from the ones we read in
class and steal their section headings.

If you are at a loss,  I recommend the pads paper or, similarly,
Kathleen's Forest paper

https://pads.cs.tufts.edu/papers/Forest2010.pdf
