### ISSUE TITLE
HW # and text mismatch

### ISSUE THREAD

**Issue by jaredchandler** [150PLD-Fall2019/Exemplars#4]
On  https://www.cs.tufts.edu/comp/150PLD/hw00-2.html

The assignment references hw00-2,

but the instructions talk about folder hw01-2.

**Comment by mpahrens** [comment]
Fixed

**Comment by jaredchandler** [comment]
So I used hw01-2 as my folder when I submitted, because I was demonstrating recall. What should I do? 

What should other people do?
