### ISSUE TITLE
Report multiple errors

### ISSUE THREAD

**Issue by jingqiyang** [150PLD-Fall2019/Exemplars#42]
Is there a way to report all errors instead of just the first one the compile-time program fails on? I feel like it would be useful to the language user to know all the problems their code has, similar to when you compile a C++ program with multiple errors.

**Comment by mpahrens** [comment]
In your languages, during the code generation phase, you can use the three different functions for reporting errors and warnings that the Q monad provides:

`reportWarning :: String -> Q ()`
reportWarning reports an warning to the user, and continues execution of code generation. Multiple calls to reportWarning from your code generator could be used to report more than one thing.
The code that is generated is still produced for use at runtime.

`reportError :: String -> Q ()`
reportError reports an error the user, and continues execution of code generation.
Multiple calls to reportError from your code generator could be used then to report more than one error.
However, unlike reportWarning, the compilation does not succeed and the codegenerated at the end is not available for use at runtime.

`fail :: String -> Q a`
fail is like report error, but it halts immediately. That is, it does not try to continue running the code generator to find more errors. 

Let me know if that helps answer your question

**Comment by jingqiyang** [comment]
sick!! thanks!!
