### ISSUE TITLE
Course Evaluations

### ISSUE THREAD

**Issue by maddoschwartz** [150PLD-Fall2019/Exemplars#43]
Hi, I was filling out the course evaluation and it's asking us to evaluate Kathleen. Is this correct? Or should we be providing feedback for Matthew.

**Comment by mpahrens** [comment]
Good question! 
I'm asking Kathleen, but in the meantime I'm guessing you can give feedback on "us" as a unit since Kathleen coached me. But, I'll get you an official answer tomorrow.

**Comment by mpahrens** [comment]
Kathleen said to write in the comments section that the evaluation is for me and not for her.
