### ISSUE TITLE
"stringPlusInt" and "stringPlusWord" clarification

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Exemplars#5]
~(double post from Readings Issues, which I will try to delete)~ (closed issue)

The second video (and text above stringPlusInt) seem to imply that stringPlusInt should return an Int, however, the type signature says (I believe) that it returns a string. Just making sure this is not a typo :)

**Comment by mpahrens** [comment]
Right, it should be a String.
I "fixed" the video.
Thanks for spotting it.
