### ISSUE TITLE
Rect functions

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#7]
Should the Largest Area functions be returning a Rect? or an Integer representing the max Area?

**Comment by mpahrens** [comment]
The Largest Area functions should be returning a Rect. 
The Rect, if checked, should have the largest possible area considering the max and min bound of it's type parameter.

**Comment by dgrotenstein** [comment]
Oh I understand. So the largestArea function is taking in the _type_, not a Rect Word8 or Int16 value, and returning the maximum Rectangle that can be made from that type?

**Comment by dgrotenstein** [comment]
Also, should width and height be absolute values, or should it take into account positive and negative values? :D
