### ISSUE TITLE
Width and Height - problems with Int16 being too large if we are using absolute value ?

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#8]
Also, should width and height be absolute values, or should it take into account positive and negative values? :D

_Originally posted by @dgrotenstein in https://github.com/150PLD-Fall2019/Exemplars/issues/7#issuecomment-529993906_

**Comment by mpahrens** [comment]
Well, I suppose its a bit of misdirection that I didn't anticipate.

width and height should not be allowed to be negative, but I suppose then the x and y coordinate doesn't matter then when calculating area, does it? I'll chock this up to me reusing an algebraic datatype from another purpose for this one.

.... the Algebraic Data Type that I had in mind was actually some `Rect' (a,a) = Rect' { lower_left_coord :: (a,a), upper_right_coord :: (a,a) }`.  Oops. Well. hopefully the exercise wasn't too much of a distraction and you get the idea that sometimes we need to ascribe types with `::` to expressions that rely on ad-hoc polymorphism.

**Comment by dgrotenstein** [comment]
So, what would you like to see for width and height for Int16? Or, could we change the Rect type to the lower left and upper right coord you suggest? Thanks!

**Comment by mpahrens** [comment]
I would just like you to use the Bounded typeclass' method `maxBound` such that width and height are the largest (max) Int16. No need to spend any more time than that.

**Comment by dgrotenstein** [comment]
Awesome, Thanks :)
